server:
  port: 8080

spring:
  application:
    name: fastfood

  datasource:
    url: jdbc:postgresql://localhost:5432/fastfood_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true