CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
                        status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
                        delivery_address VARCHAR(255) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT fk_orders_user
                            FOREIGN KEY (user_id)
                                REFERENCES users(id)
);


CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             quantity INTEGER NOT NULL CHECK (quantity > 0),
                             unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price > 0),

                             CONSTRAINT fk_order_items_order
                                 FOREIGN KEY (order_id)
                                     REFERENCES orders(id),

                             CONSTRAINT fk_order_items_product
                                 FOREIGN KEY (product_id)
                                     REFERENCES products(id),

                             CONSTRAINT uk_order_items_order_product
                                 UNIQUE (order_id, product_id)
);


CREATE INDEX idx_orders_user_id
    ON orders(user_id);


CREATE INDEX idx_order_items_order_id
    ON order_items(order_id);


CREATE INDEX idx_order_items_product_id
    ON order_items(product_id);


CREATE TRIGGER set_orders_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();